# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'nate of nine'
tagline:             ''
description:         '<a href="/"><img src="/public/n9_large.png"></a>'
url:                 http://nateofnine.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Nate Swart
  url:               https://twitter.com/nateswart
  email:             nateswart@me.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-sitemap



google_analytics: UA-61898428-2
