# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               nate of nine
tagline:             'viva la digital'
description:         '<img src="http://nateofnine.com/wp-content/uploads/2014/10/n91.png">'
url:                 http://nateofnine.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Nate Swart
  url:               https://twitter.com/nateswart
  email:             nateswart@me.com

# Custom vars
version:             1.0.0
